name: Deploy to Server on Push
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # הגדל את הזמן אם יש צורך יותר זמן

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup SSH
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          # Setup SSH and known_hosts
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          echo "SSH Setup Complete"

      # 3. Deploy to Production Server
      - name: Deploy to Production Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          echo "Starting deployment process"

          # Run deployment script over SSH with port 22
          ssh -i ~/.ssh/id_rsa -p $SERVER_PORT -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
            set -e
            echo "Navigating to project directory..."
            cd /home/$SERVER_USER/test-git-webhook || exit 1
            echo "Pulling latest code from master branch..."
            git pull origin master || exit 1
            echo "Activating virtual environment..."
            source /home/$SERVER_USER/test-git-webhook/venv/bin/activate || exit 1
            echo "Installing dependencies from requirements.txt..."
            pip install -r /home/$SERVER_USER/test-git-webhook/requirements.txt || exit 1
            echo "Restarting the application service..."
            sudo systemctl restart yolo_api.service || exit 1
            echo "Deployment complete."
          EOF
