# name: Deploy to Server on Push
# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     timeout-minutes: 1

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup SSH
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           SERVER_IP: ${{ secrets.SERVER_IP }}
#           SERVER_USER: ${{ secrets.SERVER_USER }}
#           SERVER_PORT: ${{ secrets.SERVER_PORT }}
#         run: |
#           # Setup SSH and known_hosts
#           mkdir -p ~/.ssh
#           echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
#           ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
#           echo "SSH Setup Complete"

#       - name: Deploy to Production Server
#         env:
#           SERVER_IP: ${{ secrets.SERVER_IP }}
#           SERVER_USER: ${{ secrets.SERVER_USER }}
#           SERVER_PORT: ${{ secrets.SERVER_PORT }}
#         run: |
#           # Run deployment script over SSH with verbose mode for debugging
#           echo "Starting deployment process"
#           ssh -t -i ~/.ssh/id_rsa -p $SERVER_PORT -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
#             set -e
#             echo "Step 1: Navigating to project directory..."
#             cd /home/ubuntu/test-git-webhook || exit 1
#             echo "Step 2: Pulling latest code from master branch..."
#             git pull origin master || exit 1
#             echo "Step 3: Activating virtual environment..."
#             source /home/ubuntu/test-git-webhook/venv/bin/activate || exit 1
#             echo "Step 4: Installing dependencies from requirements.txt..."
#             pip install -r /home/ubuntu/test-git-webhook/requirements.txt || exit 1
#             echo "Step 5: Restarting the application service..."
#             sudo systemctl restart yolo_api.service || exit 1
#             echo "Deployment complete."
#           EOF

name: Deploy to Server on Push
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          # Setup SSH and known_hosts
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          echo "SSH Setup Complete"

      - name: Restart the Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          # Run command to restart the application service
          echo "Restarting the application service on the server..."
          ssh -t -i ~/.ssh/id_rsa -p $SERVER_PORT -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "sudo systemctl restart yolo_api.service"
          echo "Server restart complete."
